spring:
  datasource:
    url: jdbc:h2:mem:energy-consumption
    data-username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

counterdetail:
  api:
    url: http://mycounter.com/
